// ∅ 2024 lil org

import Foundation

struct Strings {
    
    static let sendTransaction = "send transaction"
    static let signMessage = "sign message"
    static let signPersonalMessage = "sign personal message"
    static let signTypedData = "sign typed data"
    static let cancel = "cancel"
    static let ok = "ok"
    static let connecting = "connecting"
    static let somethingWentWrong = "something went wrong"
    static let failedToSend = "failed to send"
    static let failedToSign = "failed to sign"
    static let failedToSwitchChain = "failed to switch chain"
    static let tinyWallet = "tiny wallet"
    static let showWallets = "show wallets"
    static let enterWallet = "enter wallet"
    static let quit = "quit"
    static let quitTinyWallet = "quit wallet?"
    static let enableSafariExtension = "enable safari extension"
    static let dropUsALine = "yo@lil.org"
    static let viewOnGithub = "github"
    static let viewOnWarpcast = "warpcast"
    static let viewOnX = "x.com"
    static let start = "start"
    static let removeAccount = "remove account"
    static let removeWallet = "remove wallet"
    static let showPrivateKey = "show private key"
    static let showSecretWords = "show secret words"
    static let password = "password"
    static let enterKeystorePassword = "enter keystore password"
    static let importWalletTextFieldPlaceholder = "options:\n\n• private key\n• secret words\n• keystore"
    static let failedToImportWallet = "failed to import wallet"
    static let welcomeScreenText = "sign crypto\ntransactions\nin safari"
    static let createPassword = "create password"
    static let repeatPassword = "repeat password"
    static let enterPassword = "enter password"
    static let copyAddress = "copy address"
    static let viewOn = "view on"
    static let viewOnSolanaExplorer = "view on solana explorer"
    static let testnets = "testnets"
    static let backUpNewWallet = "back up new wallet"
    static let youWillSeeSecretWords = "you will see 12 secret words"
    static let removedWalletsCantBeRecovered = "removed wallets can't be recovered"
    static let removeAnyway = "remove anyway"
    static let iUnderstandTheRisks = "i understand the risks"
    static let privateKey = "private key"
    static let secretWords = "secret words"
    static let copy = "copy"
    static let canceled = "canceled"
    static let failedToVerify = "failed to verify"
    static let wallets = "wallets"
    static let selectAccount = "select account"
    static let selectNetwork = "select network"
    static let importWallet = "import wallet"
    static let addWallet = "add wallet"
    static let createNew = "create new"
    static let importExisting = "import"
    static let passwordDoesNotMatch = "password does not match"
    static let toRemoveWallet = "to remove wallet"
    static let secretWordsGiveFullAccess = "secret words give full access to your funds"
    static let privateKeyGivesFullAccess = "private key gives full access to your funds"
    static let toShowSecretWords = "to show secret words"
    static let toShowPrivateKey = "to show private key"
    static let loading = "loading"
    static let failedToLoad = "failed to load"
    static let tryAgain = "try again"
    static let noData = "there is no data yet"
    static let refresh = "refresh"
    static let nothingHere = "nothing here"
    static let pleaseTypeAtLeast = "please type at least 4 characters"
    static let unknownWebsite = "unknown website"
    static let calculating = "calculating"
    static let approveTransaction = "approve transaction"
    static let multicoinWallet = "multicoin wallet"
    static let privateKeyWallets = "private key wallets"
    static let editAccounts = "edit accounts"
    static let removingTheLastAccount = "removing the last account removes the wallet as well"
    static let selectNetworkOptionally = "select network"
    static let isSelected = "selected"
    static let data = "data"
    static let viewOnNearExplorer = "view on near explorer"
    static let sendingTransaction = "sending transaction"
    static let disconnect = "disconnect"
    static let switchAccount = "switch account"
    static let unknownNetwork = "unknown network"
    static let addAccountToConnect = "add %@ account to connect"
    static let done = "done"
    static let pinned = "pinned"
    static let mainnets = "mainnets"
    static let nonce = "nonce"
    static let gasPrice = "gas price"
    static let customNonce = "custom nonce"
    static let customGasPrice = "custom gas price"
    static let resetTo = "reset to"
    static let gwei = "gwei"
    static let fee = "fee"
    static let value = "value"
    static let to = "to"
    static let retry = "retry"
    static let uploading = "uploading"
    static let connect = "connect"
    static let paste = "paste"
    static let getStarted = "get started"
    
    private static func loc(_ string: String.LocalizationValue) -> String {
        return String(localized: string)
    }
    
}
