disabled_rules:
  - trailing_whitespace
  - file_length
  - function_body_length
  - function_parameter_count
  - type_body_length
  - line_length
  - large_tuple
  - nesting
  - cyclomatic_complexity
  - generic_type_name
  - identifier_name
  - type_name
  - weak_delegate
  - class_delegate_protocol
  - first_where
  - force_cast
  - multiple_closures_with_trailing_closure
  - force_try
  - unused_setter_value

opt_in_rules:
  - explicit_init
  - fatal_error_message
  - first_where
  - operator_usage_whitespace

excluded:
  - Pods

shorthand_operator: warning
dynamic_inline: warning
