// Copyright © 2021 Tokenary. All rights reserved.

import Foundation

struct Strings {
    
    static let sendTransaction = "Send Transaction"
    static let signMessage = "Sign Message"
    static let signPersonalMessage = "Sign Personal Message"
    static let signTypedData = "Sign Typed Data"
    static let cancel = "Cancel"
    static let ok = "OK"
    static let connecting = "Connecting"
    static let somethingWentWrong = "Something went wrong"
    static let failedToSend = "Failed to send"
    static let failedToSign = "Failed to sign"
    static let failedToSwitchChain = "Failed to switch chain"
    static let tokenary = "Tokenary"
    static let showTokenary = "Show " + tokenary
    static let enterTokenary = "Enter " + tokenary
    static let quit = "Quit"
    static let quitTokenary = "Quit Tokenary?"
    static let youWontBeAbleToSignRequests = "You won't be able to sign requests."
    static let enableSafariExtension = "Enable Safari extension"
    static let dropUsALine = "Drop us a line"
    static let viewOnGithub = "View on GitHub"
    static let viewOnTwitter = "View on Twitter"
    static let walletConnectClientDescription = "Crypto wallet for macOS"
    static let start = "Start"
    static let removeAccount = "Remove account"
    static let showPrivateKey = "Show private key"
    static let showSecretWords = "Show secret words"
    static let enterKeystorePassword = "Enter keystore password"
    static let importAccountTextFieldPlaceholder = "Options:\n\n• Ethereum Private Key\n• Secret Words\n• Keystore"
    static let failedToImportAccount = "Failed to import account"
    static let welcomeScreenText = "Sign crypto transactions.\n\nIn any browser.\n\nOn any website."
    static let createPassword = "Create Password"
    static let repeatPassword = "Repeat Password"
    static let enterPassword = "Enter Password"
    static let copyAddress = "Copy address"
    static let viewOnEtherscan = "View on Etherscan"
    static let showAccountKey = "Show account key"
    static let testnets = "Testnets"
    static let backUpNewAccount = "Back up new account"
    static let youWillSeeSecretWords = "You will see 12 secret words."
    static let removedAccountsCantBeRecovered = "Removed accounts can't be recovered."
    static let removeAnyway = "Remove anyway"
    static let iUnderstandTheRisks = "I understand the risks"
    static let privateKey = "Private key"
    static let secretWords = "Secret words"
    static let copy = "Copy"
    static let canceled = "Canceled"
    static let failedToVerify = "Failed to verify"
    static let accounts = "Accounts"
    static let selectAccountTwoLines = "Select\nAccount"
    static let selectAccount = "Select Account"
    static let selectNetwork = "Select Network"
    static let selectTestnet = "Select Testnet"
    static let importAccount = "Import Account"
    static let addAccount = "Add Account"
    static let createNew = "Create New"
    static let importExisting = "💼  Import Existing"
    static let passwordDoesNotMatch = "Password does not match"
    static let toRemoveAccount = "To remove account"
    static let secretWordsGiveFullAccess = "Secret words give full access to your funds."
    static let privateKeyGivesFullAccess = "Private key gives full access to your funds."
    static let toShowAccountKey = "To show account key"
    static let loading = "Loading"
    static let failedToLoad = "Failed to load"
    static let tryAgain = "Try again"
    static let noData = "There is no data yet"
    static let refresh = "Refresh"
    static let tokenaryIsEmpty = "Tokenary is empty"
    static let pleaseTypeAtLeast = "Please type at least 4 characters"
    static let unknownWebsite = "Unknown website ⚠️"
    static let calculating = "Calculating…"
    static let howToEnableSafariExtension = "How to enable Safari extension?"
    static let shareInvite = "Share an invite"
    
}
